version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  keycloak:
    build: .
    depends_on:
      - db
    ports:
      - 12000:8080
    expose:
      - 12000
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: change_me
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]